# Use a imagem oficial do Python
FROM python:3.12-slim

# Diretório de trabalho no contêiner
WORKDIR /app

# Copie o código do servidor para o contêiner
COPY server.py .

# Instale as dependências necessárias
RUN pip install flask

# Exponha a porta 5555 e 8888 para acesso externo
EXPOSE 5555
EXPOSE 8888
# Comando padrão a ser executado quando o contêiner for iniciado
CMD ["python", "server.py"]
