# Use a imagem oficial do Python
FROM python:3.12-slim

# Diretório de trabalho no contêiner
WORKDIR /app

# Copie o código do cliente para o contêiner
COPY client.py .

# Instale as dependências necessárias
RUN pip install requests

# Comando padrão a ser executado quando o contêiner for iniciado
CMD ["python", "client.py"]
