# Use a imagem oficial do Python
FROM python:3.12-slim

# Diretório de trabalho no contêiner
WORKDIR /app

# Copiando o código do dispositivo para o contêiner
COPY device.py .

# Expondo a porta
EXPOSE 8888

CMD ["python", "device.py"]
